apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jb2s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jb2s
    app.kubernetes.io/part-of: tkrw-pr714-0075-0063-app
  name: devfile-sample-jb2s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jb2s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jb2s
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0063-tenant/tkrw-pr714-0075-0063-app/devfile-sample-jb2s@sha256:e56e73a1d5c83b77ea12dd61bd45ec060ba8cad58acf330198629eba9ab28a88
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
